// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210415224445_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Dimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dimension");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/3/31/BlumbusTree.png",
                            Name = "Blumbus Dimension"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/2/24/Butt_Dimension.jpg",
                            Name = "Buttworld"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/e/ed/Rick-and-morty-corn-world-750x400.jpg",
                            Name = "Corn Universe"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/e/ed/Cromulon_Dimension.png",
                            Name = "Cromulon Dimension"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/e/e3/No_Image.png",
                            Name = "Cronenberg World"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/4/41/Morty_Smith.jpg",
                            Name = "Dimension 9-2184C"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/0/00/S1e1_dimension_35C.png",
                            Name = "Dimension 35-C"
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/7/7f/Dimension46Earth.png",
                            Name = "Dimension 46"
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/9/9c/Dimension_304-X.png",
                            Name = "Dimension 304-X"
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/0/02/Dimension_437.png",
                            Name = "Dimension 437"
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/8/8d/Opening_3_face_butts.png",
                            Name = "Dimension Beta B-45"
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/6/64/Dimension_C-132.png",
                            Name = "Dimension C-132"
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/9/9a/Rick-and-morty-rick-potion-number-9-cronenbergs-1280px.jpg",
                            Name = "Dimension C-137"
                        },
                        new
                        {
                            Id = 14,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/2/20/C500A_copy.jpg",
                            Name = "Dimension C-500A"
                        },
                        new
                        {
                            Id = 15,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/7/70/Summer_C-1239.png",
                            Name = "Dimension C-1239"
                        },
                        new
                        {
                            Id = 16,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/f/fd/Dimension_C-4499.png",
                            Name = "Dimension C-4499"
                        },
                        new
                        {
                            Id = 17,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/d/df/J19alpha7.png",
                            Name = "Dimension J19α7"
                        },
                        new
                        {
                            Id = 18,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/2/27/S3e7_blender_dimsension.png",
                            Name = "Dimension J19ζ7"
                        },
                        new
                        {
                            Id = 19,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/2/27/S3e7_blender_dimsension.png",
                            Name = "Dimension Zeta-6 Epsilon"
                        },
                        new
                        {
                            Id = 20,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/0/0c/S1e2_dog_world_portal.png",
                            Name = "Dog Dimension"
                        },
                        new
                        {
                            Id = 21,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/2/23/Doopidoo_Dimension.jpg",
                            Name = "Doopidoo Dimension"
                        },
                        new
                        {
                            Id = 22,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/d/df/Fantasyplanet.png",
                            Name = "Fantasy World"
                        },
                        new
                        {
                            Id = 23,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/6/62/Rick_and_Morty_Issue_29_Dimension.png",
                            Name = "Fascist dimension"
                        },
                        new
                        {
                            Id = 24,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/4/4c/S4e1_2019-11-13-12h28m17s984.png",
                            Name = "Fascist Dystopian Universe"
                        },
                        new
                        {
                            Id = 25,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/a/a0/4th_Dimensional_Time_Cop_Headquarters.png",
                            Name = "Fourth Dimension"
                        },
                        new
                        {
                            Id = 26,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/e/e4/Froopyland.png",
                            Name = "Froopyland"
                        },
                        new
                        {
                            Id = 27,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/c/cd/Furniture.png",
                            Name = "Furniture Universe"
                        },
                        new
                        {
                            Id = 28,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/1/18/Greasy_Grandma_World.jpg",
                            Name = "Glaagablaaga"
                        },
                        new
                        {
                            Id = 29,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/1/18/Greasy_Grandma_World.jpg",
                            Name = "Greasy Grandma World"
                        },
                        new
                        {
                            Id = 30,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/e/e2/Hamster_in_the_Butt_World.png",
                            Name = "Hamster in Butt World"
                        },
                        new
                        {
                            Id = 31,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/2/27/S3e7_blender_dimsension.png",
                            Name = "List of Realities"
                        },
                        new
                        {
                            Id = 32,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/3/32/A346FA1A-2CA1-42DA-B806-C1D3D33AEB3B.png",
                            Name = "Merged Universe"
                        },
                        new
                        {
                            Id = 33,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/1/16/PantlessBaseball.png",
                            Name = "Pantless Universe"
                        },
                        new
                        {
                            Id = 34,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/e/e7/2_-_One_large_sofa_chair_with_extra_chair_please.png",
                            Name = "Phone Universe"
                        },
                        new
                        {
                            Id = 35,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/1/12/Pizza_Dimension.png",
                            Name = "Pizza Universe"
                        },
                        new
                        {
                            Id = 36,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/f/f4/Post-Apocalyptic_World.png",
                            Name = "Post-Apocalyptic Dimension"
                        },
                        new
                        {
                            Id = 37,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/0/00/Replacementpaper.png",
                            Name = "Replacement dimension"
                        },
                        new
                        {
                            Id = 38,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/1/1b/Screen_Shot_2014-04-14_at_23.41.41.png",
                            Name = "Reverse Height Universe"
                        },
                        new
                        {
                            Id = 39,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/2/2f/S4e1_2019-11-13-12h35m46s019.png",
                            Name = "Shrimp Universe"
                        },
                        new
                        {
                            Id = 40,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/d/df/Testicle_Monster_Dimension.png",
                            Name = "Testicle Monster Dimension"
                        },
                        new
                        {
                            Id = 41,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/b/b1/Toilet_bathroom.png",
                            Name = "Toilet Dimension"
                        },
                        new
                        {
                            Id = 42,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/5/5a/S4e3_2019-11-28-13h16m58s807.png",
                            Name = "Tusk Dimension"
                        },
                        new
                        {
                            Id = 43,
                            Image = "https://static.wikia.nocookie.net/rickandmorty/images/f/f1/S4e1_2019-11-13-12h56m54s682.png",
                            Name = "Wasp Universe"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Morty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DimensionId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RickId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.ToTable("Morty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 14,
                            DimensionId = 1,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Blumbus Dimension)",
                            Occupation = "Student",
                            RickId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 14,
                            DimensionId = 2,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Buttworld)",
                            Occupation = "Student",
                            RickId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 14,
                            DimensionId = 3,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Corn Universe)",
                            Occupation = "Student",
                            RickId = 3
                        },
                        new
                        {
                            Id = 4,
                            Age = 14,
                            DimensionId = 4,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Cromulon Dimension)",
                            Occupation = "Student",
                            RickId = 4
                        },
                        new
                        {
                            Id = 5,
                            Age = 14,
                            DimensionId = 5,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Cronenberg World)",
                            Occupation = "Student",
                            RickId = 5
                        },
                        new
                        {
                            Id = 6,
                            Age = 14,
                            DimensionId = 6,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension 9-2184C)",
                            Occupation = "Student",
                            RickId = 6
                        },
                        new
                        {
                            Id = 7,
                            Age = 14,
                            DimensionId = 7,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension 35-C)",
                            Occupation = "Student",
                            RickId = 7
                        },
                        new
                        {
                            Id = 8,
                            Age = 14,
                            DimensionId = 8,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension 46)",
                            Occupation = "Student",
                            RickId = 8
                        },
                        new
                        {
                            Id = 9,
                            Age = 14,
                            DimensionId = 9,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension 304-X)",
                            Occupation = "Student",
                            RickId = 9
                        },
                        new
                        {
                            Id = 10,
                            Age = 14,
                            DimensionId = 10,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension 437)",
                            Occupation = "Student",
                            RickId = 10
                        },
                        new
                        {
                            Id = 11,
                            Age = 14,
                            DimensionId = 11,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension Beta B-45)",
                            Occupation = "Student",
                            RickId = 11
                        },
                        new
                        {
                            Id = 12,
                            Age = 14,
                            DimensionId = 12,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension C-132)",
                            Occupation = "Student",
                            RickId = 12
                        },
                        new
                        {
                            Id = 13,
                            Age = 14,
                            DimensionId = 13,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension C-137)",
                            Occupation = "Student",
                            RickId = 13
                        },
                        new
                        {
                            Id = 14,
                            Age = 14,
                            DimensionId = 14,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension C-500A)",
                            Occupation = "Student",
                            RickId = 14
                        },
                        new
                        {
                            Id = 15,
                            Age = 14,
                            DimensionId = 15,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension C-1239)",
                            Occupation = "Student",
                            RickId = 15
                        },
                        new
                        {
                            Id = 16,
                            Age = 14,
                            DimensionId = 16,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension C-4499)",
                            Occupation = "Student",
                            RickId = 16
                        },
                        new
                        {
                            Id = 17,
                            Age = 14,
                            DimensionId = 17,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension J19α7)",
                            Occupation = "Student",
                            RickId = 17
                        },
                        new
                        {
                            Id = 18,
                            Age = 14,
                            DimensionId = 18,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension J19ζ7)",
                            Occupation = "Student",
                            RickId = 18
                        },
                        new
                        {
                            Id = 19,
                            Age = 14,
                            DimensionId = 19,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dimension Zeta-6 Epsilon)",
                            Occupation = "Student",
                            RickId = 19
                        },
                        new
                        {
                            Id = 20,
                            Age = 14,
                            DimensionId = 20,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Dog Dimension)",
                            Occupation = "Student",
                            RickId = 20
                        },
                        new
                        {
                            Id = 21,
                            Age = 14,
                            DimensionId = 21,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Doopidoo Dimension)",
                            Occupation = "Student",
                            RickId = 21
                        },
                        new
                        {
                            Id = 22,
                            Age = 14,
                            DimensionId = 22,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Fantasy World)",
                            Occupation = "Student",
                            RickId = 22
                        },
                        new
                        {
                            Id = 23,
                            Age = 14,
                            DimensionId = 23,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Fascist dimension)",
                            Occupation = "Student",
                            RickId = 23
                        },
                        new
                        {
                            Id = 24,
                            Age = 14,
                            DimensionId = 24,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Fascist Dystopian Universe)",
                            Occupation = "Student",
                            RickId = 24
                        },
                        new
                        {
                            Id = 25,
                            Age = 14,
                            DimensionId = 25,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Fourth Dimension)",
                            Occupation = "Student",
                            RickId = 25
                        },
                        new
                        {
                            Id = 26,
                            Age = 14,
                            DimensionId = 26,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Froopyland)",
                            Occupation = "Student",
                            RickId = 26
                        },
                        new
                        {
                            Id = 27,
                            Age = 14,
                            DimensionId = 27,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Furniture Universe)",
                            Occupation = "Student",
                            RickId = 27
                        },
                        new
                        {
                            Id = 28,
                            Age = 14,
                            DimensionId = 28,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Glaagablaaga)",
                            Occupation = "Student",
                            RickId = 28
                        },
                        new
                        {
                            Id = 29,
                            Age = 14,
                            DimensionId = 29,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Greasy Grandma World)",
                            Occupation = "Student",
                            RickId = 29
                        },
                        new
                        {
                            Id = 30,
                            Age = 14,
                            DimensionId = 30,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Hamster in Butt World)",
                            Occupation = "Student",
                            RickId = 30
                        },
                        new
                        {
                            Id = 31,
                            Age = 14,
                            DimensionId = 31,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (List of Realities)",
                            Occupation = "Student",
                            RickId = 31
                        },
                        new
                        {
                            Id = 32,
                            Age = 14,
                            DimensionId = 32,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Merged Universe)",
                            Occupation = "Student",
                            RickId = 32
                        },
                        new
                        {
                            Id = 33,
                            Age = 14,
                            DimensionId = 33,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Pantless Universe)",
                            Occupation = "Student",
                            RickId = 33
                        },
                        new
                        {
                            Id = 34,
                            Age = 14,
                            DimensionId = 34,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Phone Universe)",
                            Occupation = "Student",
                            RickId = 34
                        },
                        new
                        {
                            Id = 35,
                            Age = 14,
                            DimensionId = 35,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Pizza Universe)",
                            Occupation = "Student",
                            RickId = 35
                        },
                        new
                        {
                            Id = 36,
                            Age = 14,
                            DimensionId = 36,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Post-Apocalyptic Dimension)",
                            Occupation = "Student",
                            RickId = 36
                        },
                        new
                        {
                            Id = 37,
                            Age = 14,
                            DimensionId = 37,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Replacement dimension)",
                            Occupation = "Student",
                            RickId = 37
                        },
                        new
                        {
                            Id = 38,
                            Age = 14,
                            DimensionId = 38,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Reverse Height Universe)",
                            Occupation = "Student",
                            RickId = 38
                        },
                        new
                        {
                            Id = 39,
                            Age = 14,
                            DimensionId = 39,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Shrimp Universe)",
                            Occupation = "Student",
                            RickId = 39
                        },
                        new
                        {
                            Id = 40,
                            Age = 14,
                            DimensionId = 40,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Testicle Monster Dimension)",
                            Occupation = "Student",
                            RickId = 40
                        },
                        new
                        {
                            Id = 41,
                            Age = 14,
                            DimensionId = 41,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Toilet Dimension)",
                            Occupation = "Student",
                            RickId = 41
                        },
                        new
                        {
                            Id = 42,
                            Age = 14,
                            DimensionId = 42,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Tusk Dimension)",
                            Occupation = "Student",
                            RickId = 42
                        },
                        new
                        {
                            Id = 43,
                            Age = 14,
                            DimensionId = 43,
                            Image = "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
                            Name = "Morty Smith (Wasp Universe)",
                            Occupation = "Student",
                            RickId = 43
                        });
                });

            modelBuilder.Entity("Domain.Entities.Rick", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DimensionId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.ToTable("Rick");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 70,
                            DimensionId = 1,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Blumbus Dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 2,
                            Age = 70,
                            DimensionId = 2,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Buttworld)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 3,
                            Age = 70,
                            DimensionId = 3,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Corn Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 4,
                            Age = 70,
                            DimensionId = 4,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Cromulon Dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 5,
                            Age = 70,
                            DimensionId = 5,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Cronenberg World)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 6,
                            Age = 70,
                            DimensionId = 6,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension 9-2184C)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 7,
                            Age = 70,
                            DimensionId = 7,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension 35-C)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 8,
                            Age = 70,
                            DimensionId = 8,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension 46)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 9,
                            Age = 70,
                            DimensionId = 9,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension 304-X)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 10,
                            Age = 70,
                            DimensionId = 10,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension 437)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 11,
                            Age = 70,
                            DimensionId = 11,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension Beta B-45)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 12,
                            Age = 70,
                            DimensionId = 12,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension C-132)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 13,
                            Age = 70,
                            DimensionId = 13,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension C-137)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 14,
                            Age = 70,
                            DimensionId = 14,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension C-500A)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 15,
                            Age = 70,
                            DimensionId = 15,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension C-1239)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 16,
                            Age = 70,
                            DimensionId = 16,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension C-4499)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 17,
                            Age = 70,
                            DimensionId = 17,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension J19α7)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 18,
                            Age = 70,
                            DimensionId = 18,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension J19ζ7)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 19,
                            Age = 70,
                            DimensionId = 19,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dimension Zeta-6 Epsilon)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 20,
                            Age = 70,
                            DimensionId = 20,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Dog Dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 21,
                            Age = 70,
                            DimensionId = 21,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Doopidoo Dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 22,
                            Age = 70,
                            DimensionId = 22,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Fantasy World)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 23,
                            Age = 70,
                            DimensionId = 23,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Fascist dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 24,
                            Age = 70,
                            DimensionId = 24,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Fascist Dystopian Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 25,
                            Age = 70,
                            DimensionId = 25,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Fourth Dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 26,
                            Age = 70,
                            DimensionId = 26,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Froopyland)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 27,
                            Age = 70,
                            DimensionId = 27,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Furniture Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 28,
                            Age = 70,
                            DimensionId = 28,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Glaagablaaga)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 29,
                            Age = 70,
                            DimensionId = 29,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Greasy Grandma World)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 30,
                            Age = 70,
                            DimensionId = 30,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Hamster in Butt World)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 31,
                            Age = 70,
                            DimensionId = 31,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (List of Realities)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 32,
                            Age = 70,
                            DimensionId = 32,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Merged Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 33,
                            Age = 70,
                            DimensionId = 33,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Pantless Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 34,
                            Age = 70,
                            DimensionId = 34,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Phone Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 35,
                            Age = 70,
                            DimensionId = 35,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Pizza Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 36,
                            Age = 70,
                            DimensionId = 36,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Post-Apocalyptic Dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 37,
                            Age = 70,
                            DimensionId = 37,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Replacement dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 38,
                            Age = 70,
                            DimensionId = 38,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Reverse Height Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 39,
                            Age = 70,
                            DimensionId = 39,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Shrimp Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 40,
                            Age = 70,
                            DimensionId = 40,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Testicle Monster Dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 41,
                            Age = 70,
                            DimensionId = 41,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Toilet Dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 42,
                            Age = 70,
                            DimensionId = 42,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Tusk Dimension)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        },
                        new
                        {
                            Id = 43,
                            Age = 70,
                            DimensionId = 43,
                            Image = "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
                            Name = "Rick Sanchez (Wasp Universe)",
                            Occupation = "Scientist",
                            Species = "Human (Cyborg)"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RickDimension", b =>
                {
                    b.Property<int>("RickId")
                        .HasColumnType("int");

                    b.Property<int>("DimensionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("RickId", "DimensionId");

                    b.HasIndex("Id");

                    b.ToTable("RickDimension");
                });

            modelBuilder.Entity("Domain.Entities.Morty", b =>
                {
                    b.HasOne("Domain.Entities.Dimension", "Dimension")
                        .WithMany()
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Rick", b =>
                {
                    b.HasOne("Domain.Entities.Dimension", "Dimension")
                        .WithMany()
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Morty", "Morty")
                        .WithOne("Rick")
                        .HasForeignKey("Domain.Entities.Rick", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RickDimension", b =>
                {
                    b.HasOne("Domain.Entities.Dimension", "Dimension")
                        .WithMany("RickDimensions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Rick", "Rick")
                        .WithMany("RickDimensions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
